### ISSUE TITLE
Enhancement ideas

### ISSUE THREAD

**Issue by edhager** [dojo/devtool#1]
I am reviewing dojo/devtool and dojo/diagnostics and I have a list of enhancement ideas.  FYI: I was using Chrome.

- [ ] When I created a basic Dojo 2 app and applied the diagnostic `ProjectorMixin`, I had to include dojo/stores and tslib as dependencies even though my app was not using any stores.  Can we break things up a bit in dojo/diagnostics so we only have to include dojo/stores if the application is using stores?
- [ ] When the the browser is refreshed, the Dojo 2 dev tool window needs to refresh.  Right now, you have to click the icons in the Dojo 2 pane to cause refreshes.
- [ ] I think the Dojo 2 pane should auto refresh after each vdom render.  It can be too confusing if "last render" pane shows an old render.
- [ ] As I click on nodes in the "last render" pane, I expect the browser window to scroll to the item selected or do something like Chrome's "Elements" pane where it displays a popup indicating where the node is being rendered.  Right now if you click on a node that is off screen, it can be difficult to find that node's rendering.
- [ ] When I click on a node in the "last rendering" pane, the outline should include the node's margins like Chrome's "Elements" pane does.
- [ ] When I click on a node in the "last rendering" pane and the node's classes are listed, I am seeing the CSS class names created by the compiler.  Can we display the original names from the theme?  Also, is it possible to either list the styles applied by each CSS class or provide a link that takes me to the browser's element inspection tool so I can look at the styles being applied.  Maybe more generally it would be nice to have a link for each node in the Dojo 2 "last rendering" pane that takes me to that node in the browser's element inspection tool.
- [ ] The "event log" pane needs a filtering feature to declutter the output.
- [ ] It would be nice if the "event log" pane had a feature that allowed me to configure a time threshold and any log entries that exceed that threshold are highlighted.

**Comment by smhigley** [comment]
I second the idea to show original class names in dev tools. The few times I've tried to debug styles with obfuscated classNames so far have been pretty painful.

**Comment by agubler** [comment]
Not against the idea, but in general for debugging (not necessarily dev tool related) the source maps for css should be working to help with that.

**Comment by edhager** [comment]
The Dojo 2 dev tool is not using the source maps.  It is currently showing the obfuscated class names.  It needs to show the original class names.

**Comment by agubler** [comment]
I know, I was just talking for general debugging concerns :)

**Comment by edhager** [comment]
I started working on trying to get an auto-refresh feature working for the second bullet point above.  My progress is here: https://github.com/edhager/devtool/tree/autorefresh-devtool-pane

**Comment by edhager** [comment]
Here are some thoughts...

- Chrome browser extensions have security restrictions that have to be kept in mind.  Code can run in content scripts, background scripts and scripts running in dev panes.  It can take a bit of thought to figure out how to add a new feature given the restrictions.
- Could we come up with a way that allows the diagnostic tools to plug themselves into a Dojo 2 app without modifying the Dojo 2 app?  Right now, the modifications aren't too bad; mainly just change some module import statements. But, you can't use the diagnostic tools on a production build.  How does Istanbul do it?

**Comment by umaar** [comment]
Agree with everything in this thread!

And I think this point is very important:

> Could we come up with a way that allows the diagnostic tools to plug themselves into a Dojo 2 app without modifying the Dojo 2 app

Because it could allow anyone to open up a Dojo 2 app and inspect the widget tree without having to clone/edit source code/install deps/build etc. Which is time consuming.

It has been said already but having the Widget inspector match as closely as possibly to the Elements panel (where it makes sense) I think is important too, and making it accessible - so that the tree is keyboard navigable.

**Comment by edhager** [comment]
I'm closing this issue because the conversation continues in #4.
